name: Soroban Tools e2e

on:
  push:
    branches: [main, release/**]
  pull_request:

jobs:
  integration:
    name: System tests
    strategy:
      matrix:
        scenario-filter: ["^TestDappDevelop$/^.*$"]
    runs-on: ubuntu-latest-4-cores
    env:
      # the gh tag of system-test repo version to run
      SYSTEM_TEST_GIT_REF: v1.0.18

      # the soroban tools source code to compile and run from system test
      # refers to checked out source of current git hub ref context
      SYSTEM_TEST_SOROBAN_TOOLS_REF: ${{ github.workspace }}/soroban-tools

      # core git ref should be latest commit for stable soroban functionality
      # the core bin can either be compiled in-line here as part of ci,
      SYSTEM_TEST_CORE_GIT_REF: https://github.com/stellar/stellar-core.git#875f47e247cefc25c8a4b3982ee65610e6a620e3
      SYSTEM_TEST_CORE_COMPILE_CONFIGURE_FLAGS: "--disable-tests --enable-next-protocol-version-unsafe-for-production"
      # or can use option to pull a pre-compiled image instead
      # SYSTEM_TEST_CORE_IMAGE:

      # sets the version of rust toolchain that will be pre-installed in the
      # test runtime environment, tests invoke rustc/cargo
      SYSTEM_TEST_RUST_TOOLCHAIN_VERSION: stable

      # sets the version of soroban-js-client used by tests
      SYSTEM_TEST_JS_SOROBAN_CLIENT_NPM_VERSION: "0.9.1"

      # system test will build quickstart image internally to use for running the service stack
      # configured in standalone network mode(core, rpc)
      SYSTEM_TEST_QUICKSTART_GIT_REF: https://github.com/stellar/quickstart.git#df8303380d5869272852ddb45c39abfeb7d4c938

      # triggers system test to log out details from quickstart's logs and test steps
      SYSTEM_TEST_VERBOSE_OUTPUT: "true"

      # the soroban test cases will compile various contracts from the examples repo
      SYSTEM_TEST_SOROBAN_EXAMPLES_GIT_HASH: "main"
      SYSTEM_TEST_SOROBAN_EXAMPLES_GIT_REPO: "https://github.com/stellar/soroban-examples.git"
    steps:
      - uses: actions/checkout@v3
        with:
          repository: stellar/system-test
          ref: ${{ env.SYSTEM_TEST_GIT_REF }}
          path: system-test
      - uses: actions/checkout@v3
        with:
          path: soroban-tools
      - uses: stellar/actions/rust-cache@main
      - name: Build system test with component versions
        run: |
          cd $GITHUB_WORKSPACE/system-test; \
          make \
              CORE_GIT_REF=$SYSTEM_TEST_CORE_GIT_REF \
              CORE_COMPILE_CONFIGURE_FLAGS="$SYSTEM_TEST_CORE_COMPILE_CONFIGURE_FLAGS" \
              CORE_IMAGE=$SYSTEM_TEST_CORE_IMAGE \
              SOROBAN_RPC_GIT_REF=$SYSTEM_TEST_SOROBAN_TOOLS_REF \
              SOROBAN_CLI_GIT_REF=$SYSTEM_TEST_SOROBAN_TOOLS_REF \
              RUST_TOOLCHAIN_VERSION=$SYSTEM_TEST_RUST_TOOLCHAIN_VERSION \
              QUICKSTART_GIT_REF=$SYSTEM_TEST_QUICKSTART_GIT_REF \
              JS_SOROBAN_CLIENT_NPM_VERSION=$SYSTEM_TEST_JS_SOROBAN_CLIENT_NPM_VERSION \
              build
      - name: Run system test scenarios
        run: |
          docker run --rm -t --name e2e_test stellar/system-test:dev \
          --VerboseOutput $SYSTEM_TEST_VERBOSE_OUTPUT  \
          --TestFilter "${{ matrix.scenario-filter }}" \
          --SorobanExamplesGitHash $SYSTEM_TEST_SOROBAN_EXAMPLES_GIT_HASH
